config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles

  resources :users, except: [:new]
  
  root 'pages#index'

  get 'about', to: 'pages#about'

  get 'resume', to: 'pages#resume'

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: { minimum: 3, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 15000 }
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :articles
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, 
    format: { with: VALID_EMAIL_REGEX }
    before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def create
        #render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:success] = "Article was successfully created."
            redirect_to articles_path(@article)
        else
            render 'new'
        end
    end
    
    def show
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was updated."
            redirect_to article_path(@article)
        else
            flash[:success] = "Article was not updated."
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:success] = "Article was deleted."
        redirect_to articles_path
    end

    private
        def article_params

        params.require(:article).permit(:title, :description)
        end

        def set_article
            @article = Article.find(params[:id])
        end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index
    end

    def about
    end

    def resume
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create 
        user = User.find_by(email: params[:session][:email].downcase)
        if user  && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have logged in"
            redirect_to users_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the blog #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end
       end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the blog #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @user = User.find(params[:id])
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    private
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ff9800">

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/articles/edit.html.erb
<% if logged_in? %>
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>

<%= link_to 'Back', articles_path %>
<% else %>
<% controller.redirect_to root_path %>
<% end %>

app/views/articles/index.html.erb
<h1 class="color-orange" align="center">Listing all articles</h1>
<%= render 'shared/article', obj: @articles %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<% if logged_in? %>
<h1>Create an Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path, class: 'btn btn-primary btn-large' %>
<% else %>
<% controller.redirect_to root_path %>
<% end %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<div class="well col-sm-8 col-sm-offset-2 col-xs-12">
    <% if @article.user %>
    <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
    <ul class="listing">
        <div class="row" align="center">
            <div class="col-md-4 col-md-offset-4">
                <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
                <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
            </div>
        </div>
    </ul> 
    <% end %>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
    <% if logged_in? %>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    <% else %>
    <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<% if (current_page?(root_path) || current_page?('/resume')) %>
<% else %>
<nav class="navbar navbar-custom">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "EMILE BANGMA", root_path, class: "navbar-brand", id: "logo" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><%= link_to "Articles", articles_path, class: "nav-link" %></li>
                <% if logged_in? %>
                <li><%= link_to "Create Article", new_article_path, class: "nav-link" %></li>
                <% else %>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li><%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %></li>
                <% else %>
                <li><%= link_to "Log in", login_path, class: "nav-link" %></li>
                <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= jquery_include_tag :google %>
    <%= javascript_include_tag 'application' %>

    <title>Emile Bangma</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= javascript_include_tag "rails-ujs" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render 'application/favicon' %>
    <meta name="description" content="CV/Portfolio/Blog. Computer Science student at Utrecht University"/>
    <meta name="application-name" content="Emile Bangma - Portfolio"/>
    <meta name="author" content="Emile Bangma"/>
    <meta name="google-site-verification" content="oyMdQurJrc767onv29mKYog6BKX0lN03t9Yuq3p2zC0" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom.css", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head) %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% unless (current_page?('/') || current_page?('/resume')) %>
    <div class="body-container">
      <%= yield %>
    </div>
    <% else %>
      <%= yield %>
    <% end %> 
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="color-orange">About my Blog</h1>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "index.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "fa.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "after.css", "data-turbo-track": "reload" %>
<% end %>
<!--div id="background-boxes"></div-->
<div class="wrapper">
<canvas id="bubble"></canvas>
    <header>
        <%= image_tag("background-svg.svg", class: "background-svg parallax", alt: "Background") %>
        <%= image_tag("layer-1-svg.svg", class: "layer-1-svg parallax", alt: "Layer 1") %>
        <%= image_tag("layer-2-svg.svg", class: "layer-2-svg parallax", alt: "Layer 2") %>
        <%= image_tag("layer-3-svg.svg", class: "layer-3-svg parallax", alt: "Layer 3") %>
        <%= image_tag("layer-4-svg.svg", class: "layer-4-svg parallax", alt: "Layer 4") %>
        <%= image_tag("foreground-svg.svg", class: "foreground-svg parallax", alt: "Foreground") %>
        <div>
            <h1 class="title cursive bold small">welcome to</h1>
            <h1 class="title">Emile Bangma</h1>
            <h1 class="title small">portfolio</h1>
            <h1 class="title point-down"><i class="fa fa-arrow-down"></i><h1>
        </div>
    </header>
    <section class="grid-center">
        <div class="center">
            <div id="card">
                <div id="banner-top"></div>
                <div id="banner">
                    <div id="banner-left"></div>
                    <div id="banner-right"></div>
                </div>
                <%= image_tag("emile-small.webp", id: "profile-picture", alt: "Profile picture") %>
                <h1 id="name">Emile Bangma</h1>
                <div id="typewriter-container">
                    <p class="css-replace-text" aria-label="Hi! I'm a developer">Hi! I'm a&nbsp;<span class="hidden">developer</span><span class="typewriter"></span></p>
                </div>
                <p id="icons"><a href="https://github.com/saberzero1" name="GitHub profile page" target="_blank" class="index-link" rel="noreferrer"><i class="fa fa-2x fa-github" title="GitHub Profile Page" name="GitHub Profile Page"></i></a><span class="space"></span><a href="https://www.linkedin.com/in/emilebangma/" title="LinkedIn profile page" name="LinkedIn profile page" class="index-link" target="_blank" rel="noreferrer"><i class="fa fa-2x fa-linkedin" name="LinkedIn Profile Page"></i></a><span class="space"></span><a href="https://www.instagram.com/ewjbangma/" title="Instagram profile page" name="Instagram profile page" class="index-link" target="_blank" rel="noreferrer"><i class="fa fa-2x fa-instagram" name="Instagram Profile Page"></i></a></p>
                <div class="fifty">
                    <div class="right-border"><a class="link index-link" href="resume.pdf" class="index-link" name="CV">DOWNLOAD CV<span class="space"></span><i class="fa fa-download"></i></a></div>
                    <div><a class="link index-link" href="mailto:contact@emilebangma.com" name="Mail Address">CONTACT ME<span class="space"></span><i class="fa fa-envelope"></i></a></div>
                </div>
            </div>
            <div id="container">
                <div class="content">
                    <h2 class="content-title">About Me</h2>
                </div>
                <hr>
                <div class="content">
                    <div class="content-fifty">
                        <div class="right-border-content">
                            <p class="left-text">Hello! I'm Emile Bangma.</p>
                            <p class="left-text">I'm a Computer Science student at Utrecht University.</p>
                            <p class="left-text">I have a <%= link_to 'blog', articles_url, class: "orange-link" %>.</p>
                        </div>
                        <hr class="clear-content">
                        <div>
                            <span class="text-box">Age</span><p class="right-text inline" id="ageNumber"><%= (Time.now.to_fs(:number).to_i - Date.parse("1998-01-20").to_time.to_fs(:number).to_i)/10e9.to_i %></p>
                            <hr class="clear">
                            <span class="text-box">Residence</span><p class="right-text inline">Netherlands</p>
                            <hr class="clear">
                            <span class="text-box">Address</span><p class="right-text inline">Utrecht</p>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="content">
                    <h2 class="content-title">Education</h2>
                    <hr>
                    <div class="timeline">
                    <!--div class="timeline-container timeline-right">
                        <div class="timeline-content">
                            <h3>2022 - Present</h3>
                            <p>MSc Computing Science</p>
                            <p>Utrecht University</p>
                        </div>
                    </div-->
                    <div class="timeline-container timeline-right">
                        <div class="timeline-content">
                            <h3>2018 - 2022</h3>
                            <p>BSc Computer Science</p>
                            <p>Utrecht University</p>
                        </div>
                    </div>
                </div>
                </div>
                <hr>
                <div class="content">
                    <h2 class="content-title">Work Experience</h2>
                    <hr>
                    <div class="timeline">
                    <div class="timeline-container timeline-right">
                        <div class="timeline-content">
                            <h3>2021-present</h3>
                            <p>Full-Stack Developer (volunteer)</p>
                            <p>Ichthus Utrecht</p>
                        </div>
                    </div>
                </div>
                </div>
                <hr>
                <div class="content">
                    <h2 class="content-title">Projects</h2>
                    <hr>
                    <div class="timeline">
                        <div class="timeline-container timeline-right">
                            <div class="timeline-content">
                                <a href="https://github.com/UU-tracktech/tracktech" target="_blank" rel="noreferrer"><img align="center" class="svg" src="https://github-readme-stats.vercel.app/api/pin/?username=UU-tracktech&repo=tracktech&bg_color=31313A&hide_border=true&icon_color=f99502&text_color=9c9ca1&title_color=f99502" alt="Real-time tracking of objects on multiple cameras"/></a>
                            </div>
                        </div>
                </div>
                </div>
                <hr>
                <div class="content">
                    <a href="https://github.com/saberzero1" target="_blank" rel="noreferrer"><img class="svg" src="https://github-readme-stats.vercel.app/api?username=saberzero1&show_icons=true&count_private=true&include_all_commits=true&bg_color=31313A&hide_border=true&icon_color=f99502&text_color=9c9ca1&title_color=f99502&" alt="GitHub Stats"></a>
                </div>
                <hr>
                <div class="content">
                    <a href="https://github.com/saberzero1" target="_blank" rel="noreferrer"><img class="svg" src="https://github-readme-streak-stats.herokuapp.com/?user=saberzero1&background=31313A&stroke=31313A&hide_border=true&icon_color=f99502&currStreakNum=9c9ca1&title_color=f99502&sideNums=9C9CA1&sideLabels=f99502&dates=9c9ca1" alt="GitHub Streak"></a>
                </div>
                <hr>
                <div class="content">
                    <a href="https://github.com/saberzero1" target="_blank" rel="noreferrer"><img class="svg" src="https://github-readme-stats.vercel.app/api/top-langs/?username=saberzero1&theme=gruvbox&langs_count=10&layout=compact&bg_color=31313A&hide_border=true&icon_color=f99502&text_color=9c9ca1&title_color=f99502&hide=jupyter%20notebook" alt="GitHub Language Stats"></a>
                </div>
                <p class="copy">
                    &copy; <%= DateTime.now.year %> Emile Bangma
                </p>
            </div>
        </div>
    </section>
    <!--script>
    var wh = Math.max(window.innerWidth, window.innerHeight),
        canvas = document.getElementById('bubble'),
        ctx = canvas.getContext('2d'),
        rate = 60,
        arc = 100,
        time,
        count,
        size = 7,
        speed = 20,
        lights = new Array,
        colors = ['#ff9800','#f46a49','#cc5168','#924970', '#58415f', '#31313a', '#1c1c21'];

    ctx.canvas.width = wh;
    ctx.canvas.height = wh;

    function init() {
    time = 0;
    count = 0;

    for(var i = 0; i < arc; i++) {
        lights[i] = {
        x: Math.ceil(Math.random() * wh),
        y: Math.ceil(Math.random() * wh),
        toX: Math.random() * 5 + 1,
        toY: Math.random() * 5 + 1,
        c: colors[Math.floor(Math.random()*colors.length)],
        size: Math.random() * size
        }
    }
    }

    function bubble() {
    ctx.clearRect(0,0,wh,wh);

    for(var i = 0; i < arc; i++) {
        var li = lights[i];
        
        ctx.beginPath();
        ctx.arc(li.x,li.y,li.size,0,Math.PI*2,false);
        ctx.fillStyle = li.c;
        ctx.fill();
        
        li.x = li.x + li.toX * (time * 0.05);
        li.y = li.y + li.toY * (time * 0.05);
        
        if(li.x > wh) { li.x = 0; }
        if(li.y > wh) { li.y = 0; }
        if(li.x < 0) { li.x = wh; }
        if(li.y < 0) { li.y = wh; }
    }
    if(time < speed) {
        time++;
    }
    timerID = setTimeout(bubble,1000/rate);
    }
    init();
    bubble(); 

    function resizedw() {
        if (Math.max(window.innerWidth, window.innerHeight) !== wh) {
            var canvas = document.getElementById("bubble");
            wh = Math.max(window.innerWidth, window.innerHeight);
            ctx.canvas.width = wh;
            ctx.canvas.height = wh;
            init();
            bubble(); 
        }
    }

    var resizecanvas;

    function resetcanvas() {
        clearTimeout(resizecanvas);
        resize = setTimeout(resizedw, 100);
    };

    window.addEventListener('resize', resetcanvas);
    </script-->
</div>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-12">
            <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100) %>
                <div class="article-meta-details">
                <small>Created by: <%= article.user.username if article.user %>,
                        <%= time_ago_in_words(article.created_at) %> ago,
                        last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                </div>
            </div>
            <% if logged_in? %>
            <div class="article-actions">
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
            </div>
            <% else %>
            <% end %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this object from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_message.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%= "#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<% if logged_in? %>
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :email %>
            </div>
            <div class="col-sm-8">
                <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :password %>
            </div>
            <div class="col-sm-8">
                <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
        </div>  
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
            </div>
        </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-2">
            [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
        </div> 
    </div>
</div>
<% else %>
<% controller.redirect_to root_path %>
<% end %>

app/views/users/edit.html.erb
<% if logged_in? %>
<h1 align="center">Edit User Account</h1>

<%= render 'form' %>
<% else %>
<% controller.redirect_to root_path %>
<% end %>

app/views/users/index.html.erb
<% if logged_in? %>
<h1 class="color-orange" align="center">All Users</h1>
<div align="center">
    <% @users.each do |user| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4">
                    <li><%= link_to gravatar_for(user), user_path(user) %></li>
                    <li class="article-title"><%= link_to user.username, user_path(user) %></li>
                    <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
                </div>
            </div>
        </ul>
    <% end %>
<%= will_paginate %>
</div>
<% else %>
<% controller.redirect_to %>
<% end %>

app/views/users/new.html.erb
<% if logged_in? %>
<h1 align="center">Signup</h1>

<%= render 'form' %>
<% else %>
<% controller.redirect_to root_path %>
<% end %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
    <div class="col-md-4 col-md-offset-5 center">
        <%= gravatar_for @user, size: 150 %>
    </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<%= render 'shared/article', obj: @user.articles %>
<div align="center">
    <%= will_paginate @user_articles %>
</div>